# Generated by Django 4.0.3 on 2022-03-12 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of issuer')),
                ('description', models.TextField()),
                ('short_name', models.CharField(max_length=5, verbose_name='Short name of issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Subject name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tag name')),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Coin title')),
                ('description', models.TextField(verbose_name='Coin description')),
                ('stamp', models.CharField(choices=[('simple', 'Simple'), ('3d', '3D'), ('mirror', 'Mirror')], max_length=15)),
                ('attempt', models.CharField(max_length=100, verbose_name='Coin attempt')),
                ('reverse', models.ImageField(upload_to='', verbose_name='Coin reverse')),
                ('obverse', models.ImageField(upload_to='', verbose_name='Coin obverse')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('circulation', models.IntegerField()),
                ('dimension', models.DecimalField(decimal_places=2, help_text='Dimension coin in milimeters', max_digits=4)),
                ('scales', models.DecimalField(decimal_places=2, help_text='Scales coin in grams', max_digits=4)),
                ('remarks', models.CharField(max_length=200, verbose_name='Remarks for coin')),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numiz_app.category')),
                ('designer', models.ManyToManyField(to='numiz_app.designer')),
                ('issuer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='numiz_app.issuer')),
                ('subject', models.ForeignKey(default='individual subject', on_delete=django.db.models.deletion.CASCADE, to='numiz_app.subject')),
                ('tag', models.ManyToManyField(to='numiz_app.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
