# Generated by Django 4.0.3 on 2022-03-15 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('numiz_app', '0002_alter_designer_first_name_alter_designer_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='coin',
            name='tag',
        ),
        migrations.AddField(
            model_name='coin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description of subject'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='numiz_app.category'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='circulation',
            field=models.IntegerField(help_text='mintage in the number of pieces'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='dimension',
            field=models.DecimalField(decimal_places=2, help_text='dimension coin in milimeters', max_digits=4),
        ),
        migrations.AlterField(
            model_name='coin',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numiz_app.issuer'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='obverse',
            field=models.ImageField(blank=True, upload_to='obverse/%Y/%m', verbose_name='Coin obverse'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='remarks',
            field=models.CharField(max_length=200, null=True, verbose_name='remarks for coin'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='reverse',
            field=models.ImageField(blank=True, upload_to='reverse/%Y/%m', verbose_name='Coin reverse'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='scales',
            field=models.DecimalField(decimal_places=2, help_text='scales coin in grams', max_digits=4),
        ),
        migrations.AlterField(
            model_name='coin',
            name='slug',
            field=models.SlugField(max_length=200, unique_for_date='created'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
