# Generated by Django 4.0.3 on 2022-03-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numiz_app', '0003_alter_category_options_remove_coin_tag_coin_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='Coin face value')),
                ('unit', models.CharField(choices=[('pln', 'PLN'), ('euro', 'EURO'), ('usd', 'USD'), ('aud', 'AUD'), ('gbp', 'GBP'), ('chf', 'CHF')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='face_value',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='numiz_app.currency'),
        ),
    ]
