# Generated by Django 4.0.3 on 2022-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiz_app', '0005_alter_currency_options_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='remarks for coin'),
        ),
    ]
