# Generated by Django 4.0.3 on 2022-03-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiz_app', '0006_alter_coin_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='remarks',
            field=models.CharField(max_length=200, null=True, verbose_name='remarks for coin'),
        ),
    ]
