# Generated by Django 4.0.3 on 2022-03-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numiz_app', '0007_alter_coin_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='subject',
            field=models.ForeignKey(default='Temat indywidualny', on_delete=django.db.models.deletion.CASCADE, to='numiz_app.subject'),
        ),
    ]
