# Generated by Django 4.0.3 on 2022-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiz_app', '0008_alter_coin_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='dimension',
            field=models.DecimalField(decimal_places=2, help_text='dimension coin in milimeters', max_digits=6),
        ),
        migrations.AlterField(
            model_name='coin',
            name='scales',
            field=models.DecimalField(decimal_places=2, help_text='scales coin in grams', max_digits=6),
        ),
    ]
