# Generated by Django 4.0.3 on 2022-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numiz_app', '0010_alter_coin_subject_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='issue_date',
            field=models.DateField(help_text='Format date is RRRR-MM-DD'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.IntegerField(verbose_name='Coin face value'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name of issuer'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Subject name'),
        ),
    ]
